config/routes.rb
Rails.application.routes.draw do
  resources :texts do
    member do
      get 'new_relation'
      post 'create_relation'
    end
  end

end

app/models/relation.rb
class Relation < ActiveRecord::Base
  belongs_to :text
  belongs_to :related_text, class_name: "Text"

  # after_create :create_inverse, unless: :has_inverse?
  # after_destroy :destroy_inverses, if: :has_inverse?

  # # The relation is created when one text is shoveled into
  # # the other text's related_texts. After the Relation is
  # # instantiated, the inverse relation is created.
  # def create_inverse
  #     self.class.create(inverse_relation_options)
  # end

  # def destroy_inverses
  #   inverses.destroy_all
  # end

  # # Check for presence before callback
  # def has_inverse?
  #   self.class.exists?(inverse_relation_options)
  # end

  # # finds all inverse relationships of the class calling the method
  # def inverses
  #   self.class.where(inverse_relation_options)
  # end

  # # The inverse relationship is where the related text is the
  # # text which initiated the callback, and vice versa.
  # def inverse_relation_options
  #   { related_text_id: self.text_id, text_id: self.related_text_id }
  # end
end

app/models/text.rb
class Text < ActiveRecord::Base
  has_many :relations
  has_many :related_texts, through: :relations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, except: [:index, :new, :create]

  # GET /texts
  # GET /texts.json
  def index
    @texts = Text.all
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
  end

  # GET /texts/new
  def new
    @texts = Text.new
  end

  # GET /texts/1/edit
  def edit
  end

  # GET /texts/1/new_relation
  def new_relation
    @texts = Text.all
  end

  # POST /texts/1
  def create_relation
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)

    respond_to do |format|
      if @text.save
        format.html { redirect_to @text, notice: 'Text was successfully created.' }
        format.json { render :show, status: :created, location: @text }
      else
        format.html { render :new }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to @text, notice: 'Text was successfully updated.' }
        format.json { render :show, status: :ok, location: @text }
      else
        format.html { render :edit }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    @text.destroy
    respond_to do |format|
      format.html { redirect_to texts_url, notice: 'Text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_params
      params.require(:text).permit(:title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Annotator</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <!-- Compiled and minified CSS -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/css/materialize.min.css">

  <!-- Compiled and minified JavaScript -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.5/js/materialize.min.js"></script>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
</head>
<body>

<%= yield %>

</body>
</html>

app/views/texts/_form.html.erb
<%= form_for(@text) do |f| %>
  <% if @text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
      <% @text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.text_area :content %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/texts/_relations_button.html.erb
<%= button_to create_relation_text_path, class: "waves-effect waves-light btn" do %>
  <i class="material-icons">input</i>
<% end %>

app/views/texts/_text.html.erb
<h4><%= text.title %></h4>

<p><%= text.content %></p>

app/views/texts/edit.html.erb
<h1>Editing Text</h1>

<%= render 'form' %>

<%= link_to 'Show', @text %> |
<%= link_to 'Back', texts_path %>

app/views/texts/index.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <h1>Listing Texts</h1>
  
  <table>
    <thead>
      <tr>
        <th>Title</th>
        <th>Content</th>
        <th colspan="3"></th>
      </tr>
    </thead>
  
    <tbody>
      <% @texts.each do |text| %>
        <tr>
          <td><%= text.title %></td>
          <td><%= text.content %></td>
          <td><%= link_to 'Show', text %></td>
          <td><%= link_to 'Edit', edit_text_path(text) %></td>
          <td><%= link_to 'Destroy', text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  
  <br>
  
  <%= link_to 'New Text', new_text_path %>
</div>

app/views/texts/new.html.erb
<h1>New Text</h1>

<%= render 'form' %>

<%= link_to 'Back', texts_path %>

app/views/texts/new_relation.html.erb
<div class="container">
    <div class="row">
      <div class="col s6">
        <%= render @text %>
      </div>
      <div class="col s6">
        <div class="container">
          <% @texts.each do |text| %>
            <div class="section">
              <%= render text %>
              <%= render 'relations_button' %>
            </div>
            <div class="divider"></div>
          <% end %>
        </div>
      </div>
    </div>
</div>

app/views/texts/show.html.erb
<div class="container">
  <p id="notice"><%= notice %></p>
  
  <%= render @text %>
  
  <%= link_to 'Edit', edit_text_path(@text), class: 'waves-effect waves-light btn' %> 
  <%= link_to 'Back', texts_path, class: 'waves-effect waves-light btn'%> 
  <%= link_to 'Add Relation', new_relation_text_path, class: 'waves-effect waves-light btn' %> 
</div>